stages:
  - build

job:
  stage: build
  script: 
    - echo $play
    - ~/play-1.5.2/play build-module . --framework "/home/gitlab-runner/play-1.5.2" --version "1.5.2" --require ""
  tags:
    - play